vogel/config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :characters do
    get "move_head" => "characters#move_head"
  end
end

vogel/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

vogel/app/models/character.rb
class Character < ApplicationRecord
end

vogel/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

vogel/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to character_url(@character), notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def move_head
    message = { action: 'move_head' }
    ActionCable.server.broadcast("avatar_channel", message.to_json)
    head :ok
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_url(@character), notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy!

    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.fetch(:character, {})
    end
end

vogel/app/helpers/application_helper.rb
module ApplicationHelper
end

vogel/app/helpers/characters_helper.rb
module CharactersHelper
end

vogel/app/views/characters/_character.html.erb
<div id="<%= dom_id character %>">
  <div class="avatar-container">
    <div class="avatar background"></div>
    <div class="avatar avatar-head">
      <div class="avatar avatar-hat avatar-hat-feather"></div>
      <div class="avatar avatar-eyes"></div>
    </div>
    <div class="avatar avatar-arms">
      <div class="avatar avatar-gamepad"></div>
    </div>
    <div class="avatar avatar-body"></div>
    <div class="avatar avatar-feets"></div>
  </div>
</div>

vogel/app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

vogel/app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Show this character", @character %> |
  <%= link_to "Back to characters", characters_path %>
</div>

vogel/app/views/characters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Characters</h1>

<div id="characters">
  <% @characters.each do |character| %>
    <%= render character %>
    <p>
      <%= link_to "Show this character", character %>
    </p>
  <% end %>
</div>

<%= link_to "New character", new_character_path %>

vogel/app/views/characters/new.html.erb
<h1>New character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Back to characters", characters_path %>
</div>

vogel/app/views/characters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @character %>

<button onclick="addHeadShakeAnimation()">Click me</button>

<script type="text/javascript">
  function addHeadShakeAnimation() {
    addClassToElement('avatar-head', 'avatar-head-animation-shake');
    setTimeout(function() {
      removeClassFromElement('avatar-head', 'avatar-head-animation-shake');
    }, 6000);
  }

  function addClassToElement(element, className) {
    var element = document.getElementsByClassName(element)[0];
    element.classList.add(className);
  }

  function removeClassFromElement(element, className) {
    var element = document.getElementsByClassName(element)[0];
    element.classList.remove(className);
  }
</script>

vogel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vogel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>